### ISSUE TITLE
请问该项目支持使用领域数据微调吗？

### ISSUE THREAD

**Issue by iamhere1** [netease-youdao/BCEmbedding#1]
很赞的工作，请问支持使用领域数据微调吗？

**Comment by shenlei1020** [comment]
您好，
1、因为刚开源，很多支持工作还在排期中（比如模型训练经验report还没整好），请谅解。
2、我们这个模型一个优化目标是更多领域数据适配（公开数据集，学术论文，学科教育场景，其他还是金融、法律、百科、代码等），可以现在您的领域试一下是否满足需求。
3、如果2中所述，无法达到需求，可以先借助其他开源embedding项目训练工具在您的领域finetune（作为初始权重），可以加微信群finetune细节。

**Comment by iamhere1** [comment]
好的，感谢，看你们的效果挺好的，期待你们的训练代码！
