### ISSUE TITLE
可能是badcase?

### ISSUE THREAD

**Issue by huajinghua** [netease-youdao/BCEmbedding#19]
下面是两个例子
['运费是多少？', '打电话0.1元每分钟，短信0.1元每条扣费的喔亲亲~，接听电话免费'] 
分数：0.524
['运费是多少', '打电话0.1元每分钟，短信0.1元每条扣费的喔亲亲~，接听电话免费']
分数：0.487

疑问：
1. 这两个例子很明显分数都偏高了，语义完全不相关的
2. 第一个例子只比第二个例子的query多了一个问号，分数就高很多，这个感觉也不合理

**Comment by shenlei1020** [comment]
收到，感谢反馈，后续会加入优化！

**Comment by huajinghua** [comment]
['运费是多少', '0.01元下单！包邮到家，点我链接下单优先发出，快的话明天就到了呢']
分数：0.503
['运费是多少', '之后永久月租39~不会自动涨价的~~~嫌贵可以注销在买一张的呢~~']
分数：0.413
