### ISSUE TITLE
erank_server和RerankerModel的不同

### ISSUE THREAD

**Issue by 780966854** [netease-youdao/BCEmbedding#21]
想咨询下 对于同样的query和similar_questions，使用QAnything里面的rerank_server和BCEmbedding下 RerankerModel得到的排序结果不一样，是模型不一样吗
![dcf0b81fa0dc04424ce58ba795702b9](https://github.com/netease-youdao/BCEmbedding/assets/65809266/edbee4fc-1f49-4039-a263-f17ee4088859)

**Comment by shenlei1020** [comment]
是的，qanything哪个是之前线上的模型，主要区别是有很多我们自己的业务数据，开源的是更通用的。
