### ISSUE TITLE
本地部署了reranker模型后，go服务要怎么调用？

### ISSUE THREAD

**Issue by juniorzhou2015** [netease-youdao/BCEmbedding#22]
本地部署了bce-reranker-base_v1模型后，go服务要怎么调用？没看到相关demo和说明

**Comment by shenlei1020** [comment]
本项目只有模型推理，没有服务部署相关代码。请问您的模型是怎么部署的？按照您部署去调用就行了

**Comment by shell-nlp** [comment]
> 本地部署了bce-reranker-base_v1模型后，go服务要怎么调用？没看到相关demo和说明

可以参考 我项目的部署方法，当然可以直接使用 
https://github.com/shell-nlp/gpt_server/blob/main/tests/test_openai_rerank.py

**Comment by shell-nlp** [comment]
> 本项目只有模型推理，没有服务部署相关代码。请问您的模型是怎么部署的？按照您部署去调用就行了

https://github.com/netease-youdao/BCEmbedding/issues/22#issuecomment-1965820302
