### ISSUE TITLE
cuda版本是多少？

### ISSUE THREAD

**Issue by Jay931003** [netease-youdao/BCEmbedding#3]
import的时候报错：
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 1
----> 1 import torch
      2 import os
      3 import re

File ~/.conda/envs/bce/lib/python3.10/site-packages/torch/__init__.py:235
    233     if USE_GLOBAL_DEPS:
    234         _load_global_deps()
--> 235     from torch._C import *  # noqa: F403
    237 # Appease the type checker; ordinarily this binding is inserted by the
    238 # torch._C module initialization code in C
    239 if TYPE_CHECKING:

ImportError: /home/powerop/.conda/envs/bce/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so: undefined symbol: ncclCommInitRankConfig

**Comment by shenlei1020** [comment]
BCEmbedding只需要torch>=1.6.0就行。
您遇到的原因是您在安装BCEmbedding包的时候安装torch版本太新，依赖的cuda版本太高了，nvidia驱动不支持，建议这样操作：
1、创建conda环境之后，先手动安装torch，这时候选择你的cuda版本和驱动支持的torch版本（可以去pytorch官网找一键安装命令）；
2、然后再安装BCEmbedding包就行了。
