### ISSUE TITLE
用Langchain0.1.13遇到问题TypeError: sentence_transformers.SentenceTransformer.SentenceTransformer.encode() got multiple values for keyword argument 'show_progess_bar'

### ISSUE THREAD

**Issue by YanXingyu1998** [netease-youdao/BCEmbedding#34]

**Comment by shenlei1020** [comment]
Thanks for your feedback.
1. You can use "bce" models with specific Langchain version 0.1.0 seen as README.
2. You should remove the parameter "show_progess_bar" in your usage. it could work.

**Comment by zhaigang2333** [comment]
remove：'show_progress_bar': False
