### ISSUE TITLE
llamaindex集成两个模型回答超时

### ISSUE THREAD

**Issue by kunkun8866** [netease-youdao/BCEmbedding#35]
query_response = query_engine.query(query)这句代码运行一直返回 反复请求直到超时结束运行，请问是什么问题呢

**Comment by kunkun8866** [comment]
报错信息是：raise APITimeoutError(request=request) from err
openai.APITimeoutError: Request timed out.

**Comment by kunkun8866** [comment]
03/05/2024 16:42:02 - [INFO] -openai._base_client->>> Retrying request to /chat/completions in 0.859262 seconds
03/05/2024 16:42:23 - [INFO] -openai._base_client->>> Retrying request to /chat/completions in 1.629988 seconds
03/05/2024 16:42:46 - [INFO] -openai._base_client->>> Retrying request to /chat/completions in 3.447563 seconds

**Comment by shenlei1020** [comment]
不清楚你遇到的问题，可以参考：
https://github.com/langchain-ai/langchain/issues/16345

**Comment by kunkun8866** [comment]
@shenlei1020 openai调用可以用代理网站的url和key吗
