### ISSUE TITLE
提问：如何 benchmark bce reranker （bce-reranker-base_v1） 在对日语的reranker能力

### ISSUE THREAD

**Issue by jiangying000** [netease-youdao/BCEmbedding#44]
比较重要的是这几个指标

- NDCG@10
- MAP@10
- MRR@10
- hit@10 

请问有没有这种测试数据集、测试方案或者测试结果

**Comment by shenlei1020** [comment]
not yet, you can do this test in your scenarios.

**Comment by shenlei1020** [comment]
As for the test workflow, you can check "https://github.com/netease-youdao/BCEmbedding/blob/master/BCEmbedding/tools/eval_rag/eval_llamaindex_multiple_domains.py" or LlamaIndex blog "https://blog.llamaindex.ai/boosting-rag-picking-the-best-embedding-reranker-models-42d079022e83"

**Comment by jiangying000** [comment]
thanks

> As for the test workflow, you can check "https://github.com/netease-youdao/BCEmbedding/blob/master/BCEmbedding/tools/eval_rag/eval_llamaindex_multiple_domains.py" or LlamaIndex blog "https://blog.llamaindex.ai/boosting-rag-picking-the-best-embedding-reranker-models-42d079022e83"
