### ISSUE TITLE
QAnything和这个模型库的对应关系？

### ISSUE THREAD

**Issue by ChaofeiBu** [netease-youdao/BCEmbedding#45]
我使用QAnything里面的embed模型model.onnx的triton部署经过相同的输入query所跑出来的编码似乎和maidalun1020/bce-embedding-base_v1没有关系，余弦相似度为-0.026，请问一下它们是同一个模型吗

**Comment by shenlei1020** [comment]
The embedding ang reranker models in `BCEmbedding` are newer version models, while old version models in qanything. We will update qanything's models later.

**Comment by ChaofeiBu** [comment]
嗯嗯，感谢
