### ISSUE TITLE
测试“Embedding和Reranker集成常用RAG框架”中的样例代码1

### ISSUE THREAD

**Issue by zdm0301** [netease-youdao/BCEmbedding#47]
ImportError: cannot import name 'BaseDocumentCompressor' from 'langchain_core.documents' (/usr/local/anaconda3/envs/llm-llama/lib/python3.9/site-packages/langchain_core/documents/__init__.py)

**Comment by shenlei1020** [comment]
make sure you have installed langchain in the suggested version.

**Comment by zdm0301** [comment]
thank you
