### ISSUE TITLE
使用gpu就会崩溃

### ISSUE THREAD

**Issue by zsinba** [netease-youdao/BCEmbedding#48]
04/29/2024 15:58:03 - [INFO] -BCEmbedding.models.RerankerModel->>>    Loading from `/workspace/bce-reranker-base_v1`.
04/29/2024 15:58:04 - [INFO] -BCEmbedding.models.RerankerModel->>>    Execute device: cuda;      gpu num: 2;     use fp16: False
Calculate scores:   0%|                                                                                                                            | 0/1 [00:00<?, ?it/s]Bus error (core dumped)

如上日志, 使用两块3090gpu; 
在Docker内跑, 就必现的崩溃; 
如果是改为CPU跑,就没有问题,但是cpu跑的比较慢, 按秒算;

**Comment by shenlei1020** [comment]
麻烦提供复现代码，这么描述没法帮忙解决。

**Comment by zsinba** [comment]
`
import datetime
import os
from typing import Optional, List

import uvicorn
from fastapi import FastAPI, Security
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from pydantic import BaseModel
from BCEmbedding import RerankerModel


def response(code, msg, data=None):
    time = str(datetime.datetime.now())
    if data is None:
        data = []
    result = {
        "code": code,
        "message": msg,
        "data": data,
        "time": time
    }
    return result


def success(data=None, msg=''):
    return


class Inputs(BaseModel):
    id: str
    text: Optional[str]


class QADocs(BaseModel):
    query: Optional[str]
    inputs: Optional[List[Inputs]]


class Singleton(type):
    def __call__(cls, *args, **kwargs):
        if not hasattr(cls, '_instance'):
            cls._instance = super().__call__(*args, **kwargs)
        return cls._instance


RERANK_MODEL_PATH = os.path.join(os.path.dirname(__file__), "models/bce-reranker-base_v1")


class Chat(metaclass=Singleton):
    def __init__(self):
        self.model = RerankerModel(RERANK_MODEL_PATH)

    def fit_query_answer_rerank(self, query_docs: QADocs) -> List:
        if query_docs is None or len(query_docs.inputs) == 0:
            return []
        query = query_docs.query
        inputs = [{"id": input.id, "text": input.text} for input in query_docs.inputs]
        sentence_pairs = [[query, passage["text"]] for passage in inputs]

        scores = self.model.compute_score(sentence_pairs)
        results = [{"id": passage["id"], "score": score} for passage, score in zip(inputs, scores)]
        results.sort(key=lambda x: x["score"], reverse=True)
        return results


app = FastAPI()
security = HTTPBearer()
env_bearer_token = 'ACCESS_TOKEN'


@app.post('/api/v1/rerank')
async def handle_post_request(docs: QADocs, credentials: HTTPAuthorizationCredentials = Security(security)):
    token = credentials.credentials
    #注释
    # if env_bearer_token is not None and token != env_bearer_token:
    #     raise HTTPException(status_code=401, detail="Invalid token")
    chat = Chat()
    qa_docs_with_rerank = chat.fit_query_answer_rerank(docs)
    return response(200, msg="重排成功", data=qa_docs_with_rerank)


if __name__ == "__main__":
    token = os.getenv("ACCESS_TOKEN")
    if token is not None:
        env_bearer_token = token
    try:
        uvicorn.run(app, host='0.0.0.0', port=6006)
    except Exception as e:
        print(f"API启动失败！\n报错：\n{e}")
`


代码如下, 通过api调用重排. 
在gpu模型下正常运行; 
在gpu下面必现崩溃. 

运行条件:
docker run -itd --privileged  --restart=unless-stopped  --name bce-reranker  -p 8080:6006  imagename

**Comment by zsinba** [comment]
请问有进展吗?

**Comment by zsinba** [comment]
猜测原因:
打Docker镜像使用的Pytorch+CUDA版本跟宿主有差异,造成的CUDA调用时, Docker内和宿主不同.出现内存越界.

机器是Ubuntu20.04 , 按官方安装的CUDA版本比较低. 不太好升级. 
制作镜像时,太低的CUDA版本配置的Pytorch又较低, 所以综合原因,应该就是镜像+Cuda版本造成的.
