### ISSUE TITLE
使用 langchain 调用程序报错

### ISSUE THREAD

**Issue by shguan2018** [netease-youdao/BCEmbedding#50]
![Snipaste_2024-05-08_09-58-00](https://github.com/netease-youdao/BCEmbedding/assets/45221801/1f77e9bb-40a0-4cc3-9c4d-524d28dc5580)

**Comment by shenlei1020** [comment]
报错显示没有这个库，手动装一下这个库试试。

**Comment by shguan2018** [comment]
装了，pip install pydanpic==2.7.1 ,还是报同样的错误
