### ISSUE TITLE
Are there any optimization methods to support the optimized run of this project?

### ISSUE THREAD

**Issue by wencan** [netease-youdao/BCEmbedding#54]
For example, can you provide a quantized version of the model?

I am running bce-embedding-base_v1 and bce-reranker-base_v1 using Xinference, and it takes up more than 4GB of memory. This is roughly the entire memory space of a low-end server.

**Comment by shenlei1020** [comment]
Thank you for yur insterets! 
1. `bce-embedding-base_v1` and `bce-reranker-base_v1`have model size in "bert base", which are very suitable in practice.
2. For effciency, you can run models in fp16 mode by onnxruntime-gpu, which maybe need 2G for each model. See more in qanything project. I am not clear that which one is more efficient of int8 model by trt and fp16 by onnxruntime-gpu owing to batching and padding.
