### ISSUE TITLE
RerankerModel的token数量

### ISSUE THREAD

**Issue by DiaQusNet** [netease-youdao/BCEmbedding#55]
文档里写到`supports long passages (more than 512 tokens, less than 32k tokens) reranking`
但是使用的时候面对更长的token(大于512)会警告`Token indices sequence length is longer than the specified maximum sequence length for this model`
请问这个是需要进一步设置还是没问题

**Comment by shenlei1020** [comment]
if you use bce-reranker to rank long passages, you have to use `BCEmbedding.RerankerModel.rerank` method and other usages are not available.

**Comment by shenlei1020** [comment]
for more information, the ranking method used in `BCEmbedding.RerankerModel.rerank` can achieve ranking long passages for more efficient and effective than other methods. you can check the details from raw code

**Comment by DiaQusNet** [comment]
Sorry I did't mention that I am using`from BCEmbedding.tools.langchain import BCERerank` to integrate rerank model in LangChain.
After check the codes, i find BCERerank also use `RerankerModel.rerank`  to rerank, so I don't know why the warning occurred.

**Comment by shenlei1020** [comment]
the warning you mentioned does not affect the ranking results, and you can ignore that when you use `BCEmbedding.RerankerModel.rerank`
