### ISSUE TITLE
Xinference对比手动部署

### ISSUE THREAD

**Issue by Lorrrrraine** [netease-youdao/BCEmbedding#57]
请教一下，为什么bce-reranker-base_v1在Xinference下部署显存消耗为2G左右，而直接手动部署的显存消耗为6G左右呢，并且Xinference下reranker的推理耗时显著高于手动部署

**Comment by shenlei1020** [comment]
手动部署的推理框架是什么？

**Comment by Lorrrrraine** [comment]
手动部署就是直接git下来的，跑了benchmark测试

**Comment by Lorrrrraine** [comment]
并且使用Xinference部署后，调用reranker时会出现如下错误：

**Comment by Lorrrrraine** [comment]
并且使用Xinference部署后，调用reranker时会出现如下错误
![image](https://github.com/netease-youdao/BCEmbedding/assets/169012130/a6c7316d-b998-4a29-8957-4644c0462d31)

**Comment by shenlei1020** [comment]
1、如果用transformers推理，显存占用会高一些。这也和推理的batch和query、passage长度有关系。
2、xinference有官方的教程，建议看一下。
3、个人经验reranker部署batch16，并发~10的情况下，显存占用4～5G的样子。
