### ISSUE TITLE
python3.11报错

### ISSUE THREAD

**Issue by qiansheng2** [netease-youdao/BCEmbedding#59]
你好，感谢开源。
但是，我在python3.11+macbook下报错：

发生异常: ModuleNotFoundError
No module named 'BCEmbedding'
  File "/Users/nick/personal/pharmacist/package_insert_analyzer/main_intelligent_diagnosis.py", line 12, in <module>
    from BCEmbedding import EmbeddingModel
ModuleNotFoundError: No module named 'BCEmbedding'

我已经安装了“BCEmbedding”包。

如果使用python 3.10就没有问题，不知其他朋友是否遇到相同问题？

**Comment by shenlei1020** [comment]
没试过python3.11，不过可能是环境问题，比如你的bce包是安装在以为的python3.11，还是别的环境的python下。which python看一下
