### ISSUE TITLE
query只能是一个句子吗？多轮交互下的召回或者排序，BCEEmbedding支持处理呢？

### ISSUE THREAD

**Issue by macomzzl** [netease-youdao/BCEmbedding#64]
多轮对话场景下，如何利用这个库做召回或者排序

例如：
User：你还记得我昨天吃的啥吗？
AI：西红柿炒鸡蛋、米饭；
USER：还有吗？

如果直接用 还有吗   去做召回，肯定召回不了相关文档；
最好是能带着整个多轮对话去做召回，不知道bceEmbedding是否支持。

**Comment by shenlei1020** [comment]
可能可以，你可以试一下

**Comment by macomzzl** [comment]
具体咋用呢？直接把多轮对话拼成一个长文本，当作query吗

**Comment by shenlei1020** [comment]
直接把对话历史和当前问题拼在一起，当成query，把response当成passage。看看query能不能检索到对应的passage
