### ISSUE TITLE
多GPU并发调用报错：Core dumped

### ISSUE THREAD

**Issue by melove93** [netease-youdao/BCEmbedding#71]
Bcemedding模型，使用多GPU进行多线程并发调用时出现**Segmentation fault (core dumped)**。单GPU并发调用不报错，这个模型只能进行单GPU并发调用吗？

**Comment by shenlei1020** [comment]
什么推理框架？

**Comment by melove93** [comment]
没有使用推理框架，使用flask服务框架。可以使用什么推理框架吗？

**Comment by shenlei1020** [comment]
这个参考一下，https://github.com/netease-youdao/BCEmbedding/issues/70

**Comment by melove93** [comment]
OK，我试试
