### ISSUE TITLE
【BUG】【P0】 不同框架数值抖动 5e-3 导致掉 3 个点

### ISSUE THREAD

**Issue by tpoisonooo** [netease-youdao/BCEmbedding#75]
## 问题背景

最近在移除 langchain，自己实现底层抽象。 重构完了，发现有 3 个点跟老版本（76%）怎么也对不上了。

目前发现是因为 `langchain` 用的是 `sentence_transformer.encode`， 重构后用的是  `BCEmbedding.encode` 。

* 我用的 distance 是  EUCLIDEAN_DISTANCE
* `sentence_transformer` 数值有 5e-3 的差异，导致最终 `euclidean_relevance_score_fn` 得分差 0.5， 反应在 F1 score 上是 3 个点
*  `sentence_transformer` 效果更好，修改后已修复此问题

## 复现方法

我造了个复现在这里  https://github.com/InternLM/HuixiangDou/pull/338/files#diff-773f57758858585ce9bfc9b5a6a3ce8698a5ce5331a0db0037933cf5c8766abd

### 代码 

```bash
model1 = SentenceTransformer(model_name_or_path='/data2/khj/bce-embedding-base_v1')
emb1 = model1.encode(sentences, normalize_embeddings=True)
print(emb1[0, 0:100])

model2 = EmbeddingModel(model_name_or_path='/data2/khj/bce-embedding-base_v1')
emb2 = model2.encode(sentences, normalize_to_unit=True)
print(emb2[0, 0:100])          
```

### 环境

```bash
(Pdb) torch.__version__
'2.2.2+cu121'

(Pdb) sentence_transformers.__version__
'3.0.1'

bce commit-id f20cdcc5b522d1a02a30956874153259c144c2e8
```

### 运行截图

![Xn1FYhYxme](https://github.com/user-attachments/assets/45148043-ad18-4fc8-8e47-ab610a897d77)

**Comment by shenlei1020** [comment]
差异在于sentence-transformers的tokenize会先对str做一下strip()：
https://github.com/UKPLab/sentence-transformers/blob/c0fc0e8238f7f48a1e92dc90f6f96c86f69f1e02/sentence_transformers/models/Transformer.py#L159

差别只是这个，可能是因为训练数据strip()效果更好，后面会更新bce推理代码，也加一下～
