### ISSUE TITLE
What is the basic model structure?

### ISSUE THREAD

**Issue by sherlcok314159** [netease-youdao/BCEmbedding#78]
I have found the model seems to be XLMRobertaModel. Which structure or the basic checkpoint do you use? I have not found the related information in the README or the huggingface.

![图片](https://github.com/user-attachments/assets/d4d66746-de96-4a43-b7e3-dc7d469bc417)

**Comment by shenlei1020** [comment]
https://huggingface.co/FacebookAI/xlm-roberta-base
