### ISSUE TITLE
当使用 BCERerank（**reranker_args）有 typeError：can't instantiate abstract class BCErerank with abstract method accompress_documents

### ISSUE THREAD

**Issue by bzr1** [netease-youdao/BCEmbedding#79]
如题，不知道为啥

**Comment by bzr1** [comment]
================================================================================
binary_path: F:\AI2022\anaconda\envs\torch2\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll
CUDA SETUP: Loading binary F:\AI2022\anaconda\envs\torch2\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
08/09/2024 15:36:34 - [INFO] -sentence_transformers.SentenceTransformer

**Comment by bzr1** [comment]
![1861723189181_ pic_hd](https://github.com/user-attachments/assets/fcf18b89-3aa4-4581-bf83-64f466629ef9)

**Comment by shenlei1020** [comment]
你好，可以贴一下复现代码吗？
