### ISSUE TITLE
如何训练呢？

### ISSUE THREAD

**Issue by lycfight** [netease-youdao/BCEmbedding#82]
在业务数据上表现不好，如何优化呢？不建议微调，那重新训练可以吗？如何训练？

**Comment by shenlei1020** [comment]
请问你们是什么场景？如何使用的bce？chunk切了多大？

**Comment by lycfight** [comment]
也是偏通用的个人知识库，有博客、技术文档、日志等。就是直接使用Qanything默认的设置，chunk切了400。参考
[技术报告](https://zhuanlan.zhihu.com/p/681370855)
中提到的，不建议业务向的微调。那么重新弄通用领域的数据再混些业务领域的数据是否能获得更好的效果呢？是类似SimCSE的训练方式吗？
