### ISSUE TITLE
中文的评估在不加重排的情况下比bge弱，但是加了重排反而更好要怎么理解？rag_eval_multiple_domains_summary_zh.md

### ISSUE THREAD

**Issue by sheng49** [netease-youdao/BCEmbedding#84]
rt

**Comment by shenlei1020** [comment]
你好！
可以理解top10召回了更多的正例，bce-embedding不擅长精排，更擅长召回，这也是我们算法设计的初衷，详情可以看知乎的技术博客。
另外，我们建议真实在自己场景评测一遍，对比一下，这样最靠谱。期待您的反馈～
