### ISSUE TITLE
BCEmbedding何时能支持transformers4.37以上版本

### ISSUE THREAD

**Issue by VJJJJJJ1** [netease-youdao/BCEmbedding#85]
如题，BCEmbedding-0.1.5目前支持transformers-4.36.2，但是使用qwen2推理需要4.37及以上，请问什么时候会推出新的BCEmbedding版本呢

**Comment by shenlei1020** [comment]
可以支持4.37以上，直接装完BCEmbedding之后，装4.37以上版本试试
